import "server-only";
import { hiring, getRequestWorkspaceId } from "@/lib/hiring";
import { sanitizeRichText } from "@/app/(app)/_components/sanitize-html";
import type { KickoffOutput } from "./types";

/**
 * Persist a kickoff package across hiring.jobs, hiring.sequences,
 * hiring.sequence_steps, and hiring.tasks. RLS handles workspace
 * scoping; the caller has already validated the user and the job.
 *
 * Calibration runs APPEND to sequences and tasks (Phase 1 behavior).
 * The recruiter can archive the previous sequence and mark old tasks
 * cancelled from the UI. We can add a "replace previous kickoff" toggle
 * later if accumulation becomes annoying.
 */

const KICKOFF_CHECKLIST_MARKER = "kickoff_checklist:v1";

/** Map the AI-friendly channel name to the DB sequence_step_kind enum. */
function mapChannelToKind(channel: string): {
  kind: "email" | "linkedin_message" | "manual_task";
  task_title?: string;
} {
  switch (channel) {
    case "email":
      return { kind: "email" };
    case "linkedin_message":
      return { kind: "linkedin_message" };
    case "linkedin_invitation":
      return {
        kind: "manual_task",
        task_title: "Send LinkedIn connection request",
      };
    case "linkedin_inmail":
      return { kind: "manual_task", task_title: "Send LinkedIn InMail" };
    default:
      return { kind: "manual_task", task_title: `Step (${channel})` };
  }
}

export async function persistKickoff(input: {
  jobId: string;
  jobTitle: string;
  output: KickoffOutput;
}): Promise<void> {
  const workspaceId = await getRequestWorkspaceId();
  const db = await hiring();

  // 1. Update jobs with the generated content. public_description gets
  //    sanitized — Claude returns HTML targeted at Tiptap.
  const interviewScript = input.output.talental_interview_script
    ? { markdown: input.output.talental_interview_script }
    : null;

  const { error: jobErr } = await db
    .from("jobs")
    .update({
      public_description: sanitizeRichText(input.output.jd_public_description),
      overview: input.output.overview,
      requirements: input.output.requirements,
      sourcing: input.output.sourcing,
      hiring_process: input.output.hiring_process,
      interview_script: interviewScript,
      linkedin_post: input.output.linkedin_post || null,
      assessment_content: input.output.assessment_content || null,
    })
    .eq("id", input.jobId);
  if (jobErr) {
    throw new Error(`Failed to update job: ${jobErr.message}`);
  }

  // 2. Outreach sequence (only when present).
  if (input.output.outreach_sequence && input.output.outreach_sequence.length > 0) {
    const { data: seq, error: seqErr } = await db
      .from("sequences")
      .insert({
        workspace_id: workspaceId,
        name: `${input.jobTitle} — Outreach`,
        description:
          "Generated by Kickoff. Refine and activate manually before launching.",
        status: "draft",
        target_entity_type: "candidate",
        default_job_id: input.jobId,
      })
      .select("id")
      .single();
    if (seqErr || !seq) {
      throw new Error(`Failed to create sequence: ${seqErr?.message}`);
    }

    const stepsPayload = input.output.outreach_sequence.map((s) => {
      const mapped = mapChannelToKind(s.channel);
      return {
        workspace_id: workspaceId,
        sequence_id: seq.id as string,
        position: s.step,
        kind: mapped.kind,
        delay_minutes: s.delay_hours * 60,
        subject_template: s.subject ?? null,
        body_template: s.body ?? null,
        task_title: mapped.task_title ?? null,
        task_body:
          mapped.task_title && s.body ? s.body : null,
        config: { channel: s.channel },
      };
    });

    const { error: stepsErr } = await db
      .from("sequence_steps")
      .insert(stepsPayload);
    if (stepsErr) {
      throw new Error(`Failed to create sequence steps: ${stepsErr.message}`);
    }
  }

  // 3. Kickoff checklist as tasks.
  if (
    input.output.kickoff_checklist &&
    input.output.kickoff_checklist.length > 0
  ) {
    const tasksPayload = input.output.kickoff_checklist.map((item) => ({
      workspace_id: workspaceId,
      title: item.item,
      // Marker in the body lets us filter / clean up kickoff-generated
      // tasks separately from manually created ones in a later phase.
      body: `<!-- ${KICKOFF_CHECKLIST_MARKER} | phase: ${item.phase} | indent: ${item.indent} -->`,
      status: "open" as const,
      priority: "normal" as const,
      entity_type: "job" as const,
      entity_id: input.jobId,
    }));

    const { error: tasksErr } = await db.from("tasks").insert(tasksPayload);
    if (tasksErr) {
      throw new Error(`Failed to create kickoff tasks: ${tasksErr.message}`);
    }
  }
}
