/**
 * SOP (Standard Operating Procedure) template for every role we work.
 *
 * The list is intentionally hard-coded — it's the company-wide playbook,
 * NOT a per-job checklist generated by the kickoff prompt. Checked-state
 * persists per vacante via hiring.tasks rows marked with
 * `<!-- sop:v1 | item: ITEM_ID -->`; missing items are seeded the first
 * time the SOP tab opens for a vacante (see paquete/page.tsx).
 *
 * Ordering, indent, and phase grouping below ARE the SOP. If we want to
 * add a step, remove a step, or rename one, this file is the source of
 * truth. Existing hiring.tasks rows with item IDs no longer in the
 * template become orphans (not rendered, harmless).
 */

export type SopPhaseKey =
  | "admin"
  | "kickoff"
  | "calibration"
  | "sourcing"
  | "reports"
  | "interviews"
  | "preoffer"
  | "offer";

export type SopItem = {
  /** Stable ID — DO NOT change once shipped; it's the join key against
   *  the hiring.tasks rows in DB. New steps need a NEW id. */
  id: string;
  phase: SopPhaseKey;
  /** 0 = top-level step. 1 = sub-step (rendered indented). */
  indent: 0 | 1;
  /** Title shown in the recruiter UI. Localized lookups happen in the
   *  React component via t(`sop.items.${id}`). */
  labelEs: string;
  labelEn: string;
};

export const SOP_PHASES: ReadonlyArray<{
  key: SopPhaseKey;
  labelEs: string;
  labelEn: string;
}> = [
  { key: "admin", labelEs: "Admin", labelEn: "Admin" },
  { key: "kickoff", labelEs: "Kickoff", labelEn: "Kickoff" },
  { key: "calibration", labelEs: "Calibración", labelEn: "Calibration" },
  { key: "sourcing", labelEs: "Sourcing & Outreach", labelEn: "Sourcing & Outreach" },
  { key: "reports", labelEs: "Candidate Reports & Envío", labelEn: "Candidate Reports & Submission" },
  { key: "interviews", labelEs: "Entrevistas con cliente", labelEn: "Client Interviews" },
  { key: "preoffer", labelEs: "Pre-oferta", labelEn: "Pre-offer" },
  { key: "offer", labelEs: "Oferta y Placement", labelEn: "Offer & Placement" },
] as const;

export const SOP_TEMPLATE: ReadonlyArray<SopItem> = [
  // ── Admin ─────────────────────────────────────────────────────────
  {
    id: "admin-retainer",
    phase: "admin",
    indent: 0,
    labelEs: "Calcular el retainer y registrarlo en el archivo de finanzas",
    labelEn: "Calculate retainer and log it in the finance file",
  },
  {
    id: "admin-agreement-bill",
    phase: "admin",
    indent: 0,
    labelEs: "Enviar Agreement y Down Payment Bill",
    labelEn: "Send Agreement and Down Payment Bill",
  },
  {
    id: "admin-confirm-down",
    phase: "admin",
    indent: 0,
    labelEs: "Confirmar el pago del anticipo",
    labelEn: "Confirm down-payment receipt",
  },

  // ── Kickoff ───────────────────────────────────────────────────────
  {
    id: "kickoff-create-job",
    phase: "kickoff",
    indent: 0,
    labelEs: "Crear la vacante en el ATS",
    labelEn: "Create the vacancy in the ATS",
  },
  {
    id: "kickoff-review-jd",
    phase: "kickoff",
    indent: 0,
    labelEs:
      "Leer y revisar el JD para que tenga sentido, no suene a IA, etc.",
    labelEn: "Read and review the JD so it makes sense and doesn't sound AI-cheesy",
  },
  {
    id: "kickoff-publish",
    phase: "kickoff",
    indent: 0,
    labelEs:
      "Publicar la vacante en la página de carreras (y opcionalmente en job boards externos)",
    labelEn:
      "Publish the vacancy on the careers page (and optionally on external job boards)",
  },
  {
    id: "kickoff-snippety-link",
    phase: "kickoff",
    indent: 0,
    labelEs: "Agregar el link de la vacante a Snippety",
    labelEn: "Add the vacancy link to Snippety",
  },
  {
    id: "kickoff-snippety-interview",
    phase: "kickoff",
    indent: 0,
    labelEs: "Revisar el formato de entrevista y agregarlo a Snippety",
    labelEn: "Review the interview format and add it to Snippety",
  },
  {
    id: "kickoff-review-outreach",
    phase: "kickoff",
    indent: 0,
    labelEs: "Revisar el Outreach Sequence",
    labelEn: "Review the outreach sequence",
  },
  {
    id: "kickoff-seed-client-candidates",
    phase: "kickoff",
    indent: 0,
    labelEs:
      "Agregar candidatos que el cliente ya tenga activos (opcional, evita duplicados)",
    labelEn:
      "Add candidates the client already has active (optional, prevents duplicate outreach)",
  },
  {
    id: "kickoff-send-email",
    phase: "kickoff",
    indent: 0,
    labelEs: "Enviar el kickoff email al cliente",
    labelEn: "Send the kickoff email to the client",
  },

  // ── Calibration ───────────────────────────────────────────────────
  {
    id: "calibration-send-batch",
    phase: "calibration",
    indent: 0,
    labelEs: "Buscar de 10 a 15 perfiles y enviarlos al cliente para feedback",
    labelEn: "Source 10–15 profiles and send them to the client for feedback",
  },
  {
    id: "calibration-receive-feedback",
    phase: "calibration",
    indent: 0,
    labelEs: "Recibir el feedback del cliente sobre la calibración",
    labelEn: "Receive the client's calibration feedback",
  },

  // ── Sourcing & Outreach (objetivo: 20-30 perfiles) ────────────────
  {
    id: "sourcing-internal-db",
    phase: "sourcing",
    indent: 1,
    labelEs: "Sourcing en nuestra base de datos interna",
    labelEn: "Source from our internal database",
  },
  {
    id: "sourcing-pin",
    phase: "sourcing",
    indent: 1,
    labelEs: "Sourcing en PIN",
    labelEn: "Source on PIN",
  },
  {
    id: "sourcing-happenstance",
    phase: "sourcing",
    indent: 1,
    labelEs: "Sourcing en Happenstance",
    labelEn: "Source on Happenstance",
  },
  {
    id: "sourcing-referrals",
    phase: "sourcing",
    indent: 1,
    labelEs: "Pedir referrals",
    labelEn: "Ask for referrals",
  },
  {
    id: "sourcing-whatsapp",
    phase: "sourcing",
    indent: 1,
    labelEs: "WhatsApp Groups",
    labelEn: "WhatsApp groups",
  },
  {
    id: "sourcing-sales-nav",
    phase: "sourcing",
    indent: 1,
    labelEs: "LinkedIn Sales Navigator",
    labelEn: "LinkedIn Sales Navigator",
  },
  {
    id: "sourcing-xray",
    phase: "sourcing",
    indent: 1,
    labelEs: "X-Ray con Claude o Perplexity",
    labelEn: "X-Ray search with Claude or Perplexity",
  },
  {
    id: "sourcing-launch-campaign",
    phase: "sourcing",
    indent: 0,
    labelEs: "Lanzar la campaña de outreach a todos los candidatos",
    labelEn: "Launch the outreach campaign to all sourced candidates",
  },

  // ── Candidate Reports & Submission ────────────────────────────────
  {
    id: "reports-create",
    phase: "reports",
    indent: 0,
    labelEs:
      "Crear Candidate Reports (mínimo 2 candidatos muy buenos, idealmente 3)",
    labelEn: "Write Candidate Reports (minimum 2 strong candidates, ideally 3)",
  },
  {
    id: "reports-send",
    phase: "reports",
    indent: 0,
    labelEs:
      "Enviar candidatos al cliente (uno por uno o en batch, según prefiera)",
    labelEn: "Send candidates to the client (one-by-one or batch, per preference)",
  },

  // ── Client Interviews (cycle, repeats per round) ──────────────────
  {
    id: "interviews-schedule",
    phase: "interviews",
    indent: 0,
    labelEs:
      "Agendar entrevistas con el cliente (scheduling poll o disponibilidad directa)",
    labelEn:
      "Schedule client interviews (scheduling poll or direct availability)",
  },
  {
    id: "interviews-run",
    phase: "interviews",
    indent: 0,
    labelEs: "Realizar las entrevistas con el cliente",
    labelEn: "Run the client interviews",
  },
  {
    id: "interviews-feedback",
    phase: "interviews",
    indent: 0,
    labelEs:
      "Recibir feedback / debrief del cliente (SLA: 48h para responder)",
    labelEn:
      "Receive client feedback / debrief (SLA: 48h for the client to respond)",
  },

  // ── Pre-offer (selected candidate) ────────────────────────────────
  {
    id: "preoffer-comp-info",
    phase: "preoffer",
    indent: 0,
    labelEs: "Pedir información de compensación completa al candidato",
    labelEn: "Request full compensation information from the candidate",
  },
  {
    id: "preoffer-bg-check",
    phase: "preoffer",
    indent: 0,
    labelEs:
      "Realizar background check (si la empresa cliente no lo hace por su cuenta)",
    labelEn:
      "Run the background check (unless the client company does it themselves)",
  },

  // ── Offer & Placement ─────────────────────────────────────────────
  {
    id: "offer-extend",
    phase: "offer",
    indent: 0,
    labelEs: "Pasar a la oferta y obtener aceptación",
    labelEn: "Extend the offer and secure acceptance",
  },
  {
    id: "offer-placement-email",
    phase: "offer",
    indent: 0,
    labelEs: "Enviar el placement email al cliente",
    labelEn: "Send the placement email to the client",
  },
  {
    id: "offer-followup-1m",
    phase: "offer",
    indent: 0,
    labelEs: "Follow-up al mes del placement",
    labelEn: "Follow up 1 month after placement",
  },
  {
    id: "offer-followup-3m",
    phase: "offer",
    indent: 0,
    labelEs: "Follow-up antes de los 3 meses (garantía)",
    labelEn: "Follow up before the 3-month mark (guarantee window)",
  },
] as const;

/** Marker comment we write into hiring.tasks.body so we can recover the
 *  item id later. Kept in sync with the regex in paquete/page.tsx. */
export const SOP_MARKER_PREFIX = "sop:v1";

export function sopMarker(itemId: string): string {
  return `<!-- ${SOP_MARKER_PREFIX} | item: ${itemId} -->`;
}
